### ISSUE TITLE
Multiple site config

### ISSUE THREAD

**Issue by aaademosu** [mubrik/sharepoint-WB-PDP#2]
List names are hardcoded, how can that be passed in as config data?

Referring to.

https://github.com/mubrik/sharepoint-WB-PDP/blob/master/src/webparts/hRpersonalDevPlan/controller/server.ts#L31

https://github.com/mubrik/sharepoint-WB-PDP/blob/master/src/webparts/hRpersonalDevPlan/controller/server.ts#L41

**Comment by mubrik** [comment]
config data? i'm not sure why that is necessary?
Is the issue the hardcoded names or that it cant be changed by user?

**Comment by aaademosu** [comment]
not an issue, just an observation. Better to have such data configured to make change easy.
