### ISSUE TITLE
Years hardcoded

### ISSUE THREAD

**Issue by aaademosu** [mubrik/sharepoint-WB-PDP#6]
this shouldn't be hardcoded. Can we build an array from date objects.  We don't want to be manually adding dates

https://github.com/mubrik/sharepoint-WB-PDP/blob/master/src/webparts/hRpersonalDevPlan/components/form/YearGoalForm.tsx#L61

**Comment by mubrik** [comment]
Fixed in single branch

https://github.com/mubrik/sharepoint-WB-PDP/blob/7e35cb2409c3bed87d70c863f5ccbdce2eb37158/src/webparts/hRpersonalDevPlan/components/form/YearGoalForm.tsx#L84
