### ISSUE TITLE
Labelling?

### ISSUE THREAD

**Issue by aaademosu** [mubrik/sharepoint-WB-PDP#7]
Review.

Inconsistent casing

https://github.com/mubrik/sharepoint-WB-PDP/blob/master/src/webparts/hRpersonalDevPlan/components/form/BioDataForm.tsx#L62

https://github.com/mubrik/sharepoint-WB-PDP/blob/master/src/webparts/hRpersonalDevPlan/components/form/BioDataForm.tsx#L66

**Comment by mubrik** [comment]
Fixed in single branch 

https://github.com/mubrik/sharepoint-WB-PDP/blob/7e35cb2409c3bed87d70c863f5ccbdce2eb37158/src/webparts/hRpersonalDevPlan/components/form/BioDataForm.tsx#L48
